name: build
on: [ push, pull_request, workflow_dispatch ]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew build check dokkaHtml

      - run: ./gradlew publish
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'alexandrepiveteau/kotlin-graphs' }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Deploy docs
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'alexandrepiveteau/kotlin-graphs' }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cd build/dokka/html
          git init . && git branch -m dokka
          git add .
          git config user.name "${{github.actor}}"
          git config user.email "${{github.actor}}@users.noreply.github.com"
          git commit -m "🚀 Publish documentation"
          git remote add origin https://x-access-token:$GITHUB_TOKEN@github.com/${{github.repository}}
          git push -u origin dokka --force
